name: Install and configure argoCD
run-name: Install and configure argoCD
on: [push]
env:
  CLUSTER_NAME: dockercoins-cluster-teo
  CLUSTER_ZONE: europe-west1-b
  PROJECT_NAME: teolia-school-devops

jobs:
  InstallAndConfigureArgoCD:
    name: Install and configure ArgoCD.
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:

      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Install plugin auth
        run: |
          REPO_URL="https://packages.cloud.google.com/apt"
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] $REPO_URL cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list >/dev/null
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin  
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_KEY }}'
          token_format: 'access_token'
  
      - name: Authenticate to GKE cluster
        run: |   
          gcloud container clusters get-credentials \
          ${{ env.CLUSTER_NAME }} --zone ${{ env.CLUSTER_ZONE }} --project ${{ env.PROJECT_NAME }}
      - name: Install and configure ArgoCD
        run: |
            if [[ $(kubectl get namespaces | grep -c argocd) == 0 ]]
                then
                    kubectl create namespace argocd
            else
                echo "Namespace already exist"
            fi            
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/core-install.yaml
            # Apply ArgoCD config file
            kubectl apply -f argocd-app.yml
